# Install pre-commit hooks via:
# pre-commit install

# yapf = yet another python formatter
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.28.0
  hooks:
  - id: yapf
    name: yapf
    args: ["-i"]

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.63'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]

-   repo: https://github.com/PyCQA/pylint
    rev: v2.8.2
    hooks:
    -   id: pylint
        language: system
        args: [
            '--ignore=E0012'
        ]